### ISSUE TITLE
Support for Sharepoint

### ISSUE THREAD

**Issue by rvaheldendaten** [QlikDeploymentFramework/Qlik-Deployment-Framework-Cloud#1]
Hello!

Instead of putting the Deployment Framework to a ONE Drive, I would love to use the Sharepoint Connector and store the files over there (typically I need extra Admin OFFICE 365 rights to connect to ONE Drive, while Sharepoint Connector often works out of the box at the customer).

After long discussions with Qlik Support (Support Case 00081114) Sharepoint Connector can not read files with point '.' character on filepath.

Here an example:

We have configured the Office 365 Sharepoint Connector on our cloud tenant
 
Unfortunately we are not able to read flatfiles (.csv, .xlsx) if the path in the sharepoint Lib:// statement contains a point "." character. We are unable to preview the file, and therefore we are unable to generate the load statement.  According to Qlik Support this is a WAD (working as designed).

![image](https://github.com/QlikDeploymentFramework/Qlik-Deployment-Framework-Cloud/assets/11175181/38a3a702-84d9-4db4-86df-c1a961fd52f1)

If we replace the "." in the path and put for example a "_" instead, the same .xlsx File can be read successfully.  

![image](https://github.com/QlikDeploymentFramework/Qlik-Deployment-Framework-Cloud/assets/11175181/3a6f610e-6086-432d-9427-18a9131a785c)

Are there any chances to rework the Deployment framework to use '_' in the folder structure instead of '.'. Or do I have to go for One-Drive?

**Comment by QlikDeploymentFramework** [comment]
Hi Roland, all good with you? Sorry late reply have been on vacation, Is this only folders that can not have a "." in the name? If so I can probably do a workaround for folders in SaaS version of QDF, as the framework is identifying QDF folders by searching for a Info.txt file and not by the actually foldername itself. /Cheers

**Comment by rvaheldendaten** [comment]
HI Magnus!

Good to hear you! I was on vacation as well! Yes it's just about "." in **folder** names.  If I can test something, just ping me!

Thx,
Roland

**Comment by QlikDeploymentFramework** [comment]
Pleas look into the InitLink.qvs code and see if you can "purge" the foldername (that becomes the Global variable name) by something optional (we need to keep . as an option), The "purge" action is done in two places by
` let vL.QDF.Foldername =purgechar(subfield('$(vL.QDF.DoDir)','.',-1), '/');`
 One option is to allow removal the numbers all together thereby allowing the variants 02.QVD and QVD
Thx /Magnus
https://github.com/QlikDeploymentFramework/Qlik-Deployment-Framework-Cloud/blob/main/InitLink.qvs

**Comment by QlikDeploymentFramework** [comment]
Hi @rvaheldendaten I have now updated QDF allowing you to remove the number+. in QDF folders (01.QVD vs QVD). As long as there is a info.txt file in the folder QDF will identify this and create a global variable that matches the foldername.. Please test and get back to me if it works of there is any issues

**Comment by rvaheldendaten** [comment]
hi! Thx! Sorry for my late response! I will test next week!

Thx,
Roland

**Comment by rvaheldendaten** [comment]
HI Magnus!

You mean renaming all Folders, similar to this screenshot?
![image](https://github.com/QlikDeploymentFramework/Qlik-Deployment-Framework-Cloud/assets/11175181/ee8599d3-bc62-4479-9575-38a7c7292c2c)


I'm currently stuck when tryp to load the "Custom.Variable.csv". From the logfiles I think the variable $(vG.$(vL.QDF.SharedInclude)BaseVariablePath) is empty. Any ideas why this could happen?

Thx,
Roland

**Comment by QlikDeploymentFramework** [comment]
No remove number and divider all together and just keep the folder name like “QVD” or “Include“ hope this helps 
![image](https://github.com/QlikDeploymentFramework/Qlik-Deployment-Framework-Cloud/assets/23187088/825ac094-c122-4ba5-a191-c7e2a342e304)
